apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    env: prod
    owner: ArtemTabolich
spec:
  selector:
    project: {{ .Release.Name }}
  type: NodePort
  ports:
    - name: nginx-listener
      protocol: TCP
      port: 80
      targetPort: 80
